### PR TITLE
libtrap: return values in tls and tcpip interfaces fixed; closes #82

### LINKED ISSUE #82: libtrap: Wrong return value handling in tcpip and tls interface
During connection to TCP socket in both tcpip and tls interface if there an error occures (i.e. TRAP_E_TIMEOUT)

https://github.com/CESNET/Nemea-Framework/blob/master/libtrap/src/ifc_tcpip.c#L861
https://github.com/CESNET/Nemea-Framework/blob/master/libtrap/src/ifc_tls.c#L1011

After setting return value rv to some error the function can still go to end and return TRAP_E_OK which is clearly not intended.

Expected behavior:
Set rv respectively in function and in the end return rv instead of implicit TRAP_E_OK.

### PR DESCRIPTION
**Pull request by jaroslavh**
Added check for return value of tcp socket connection to both interfaces. If it failed, function will end with proper TRAP error code.

Fixed problem with not notifying user that libtrap will be installed without tls interface and then failing on executing tests for tls.

Few minor coding style changes.

### CODE REVIEW

File: libtrap/src/ifc_tcpip.c [hunk 1]
```diff
@@ -894,13 +892,17 @@ static int client_socket_connect(void *priv, const char *dest_addr, const char *
             p = (struct addrinfo *) &addr.unix_addr;
          }
       } else {
```
Comment (cejkato2) [inline libtrap/src/ifc_tcpip.c]: I expect there should be:
`rv = TRAP_E_OK;` before `} else {`

File: libtrap/src/ifc_tcpip.c [hunk 2]
```diff
@@ -804,7 +802,7 @@ static int client_socket_connect(void *priv, const char *dest_addr, const char *
    int sockfd = -1, options;
    union tcpip_socket_addr addr;
    struct addrinfo *servinfo, *p = NULL;
-   int rv, addr_count = 0;
+   int rv = 0, addr_count = 0;
```
Comment (cejkato2) [inline libtrap/src/ifc_tcpip.c]: `rv` can remain uninitialized because it is anyway rewritten on Line 821 (`getaddrinfo`) for `TCPIP` and it should be set according to my following comment for `UNIX` IFC.

File: libtrap/src/ifc_tls.c [hunk 3]
```diff
@@ -1022,18 +1015,24 @@ static int client_socket_connect(tls_receiver_private_t *c, struct timeval *tv)
...
+   }
+
+   /* catching all possible errors from setting up socket before atempting tls handshake */
+   if (rv != TRAP_E_OK) {
+      CHECK_AND_FREE(servinfo, freeaddrinfo);
+      return rv;
+   }
 
    if (p != NULL) {
       inet_ntop(p->ai_family, get_in_addr((struct sockaddr *)p->ai_addr), s, sizeof s);
```
Comment (cejkato2) [inline libtrap/src/ifc_tls.c]: This PR adds check for the return value of `inet_ntop()` in ifc_tcpip.c -> It should be the same here.

File: libtrap/src/ifc_tls.c [hunk 4]
```diff
@@ -1022,18 +1015,24 @@ static int client_socket_connect(tls_receiver_private_t *c, struct timeval *tv)
...
    CHECK_AND_FREE(servinfo, freeaddrinfo); /* all done with this structure */
 
-   if (p == NULL) {
-      VERBOSE(CL_VERBOSE_LIBRARY, "recv client: Connection failed.");
-      return TRAP_E_TIMEOUT;
-   }
-
    c->sd = sockfd;
    c->ssl = SSL_new(c->sslctx);
    SSL_set_fd(c->ssl, c->sd);
```
Comment (cejkato2) [inline libtrap/src/ifc_tls.c]: This comment is for Line 1109: `return TRAP_E_OK` -> probably the same issue as in ifc_tcpip.c

Comment (jaroslavh) [reply libtrap/src/ifc_tls.c]: Here I think that TRAP_E_OK is ok. Because in case of TLS if we get here, there really was no problem.

I check for problems in socket setup here: https://github.com/jaroslavh/Nemea-Framework/blob/master/libtrap/src/ifc_tls.c#L1025

On lines below, I did not come up with better solution than return on the spot, because I need to stop before the negotiation. What I mean are lines 1057 and 1067.
